# KUBEX Worker Agent Startup Script
# This runs the local engine that builds your Docker images and spawns Localtunnels.

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "        KUBEX LOCAL WORKER AGENT         " -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""

# Check for Docker Desktop
Write-Host "Checking for Docker Engine..." -ForegroundColor Yellow
$dockerCheck = Get-Command "docker" -ErrorAction SilentlyContinue
if (-not $dockerCheck) {
    Write-Host "ERROR: Docker is not installed or not in PATH." -ForegroundColor Red
    Write-Host "Please install Docker Desktop and start it before running KUBEX." -ForegroundColor Red
    exit 1
}
Write-Host "✅ Docker Engine found." -ForegroundColor Green

# Use localhost if testing locally, or a remote URL if the control plane is deployed
$ApiServerUrl = "http://localhost:3001"
if ($env:API_SERVER_URL) {
    $ApiServerUrl = $env:API_SERVER_URL
}
Write-Host "🔌 Connecting to Control Plane at: $ApiServerUrl" -ForegroundColor Green

# Start the worker agent
Write-Host "🚀 Starting Worker Agent (Auto-Tunnel Enabled)..." -ForegroundColor Yellow
Set-Location -Path ".\worker-agent"

# Set necessary environment variables
$env:API_SERVER_URL = $ApiServerUrl
$env:NODE_ID = "kubex-local-laptop"
# We generate a dummy token for local dev, normally this is generated by the UI
$env:KUBEX_TOKEN = "797e9bd139a48c6f27a16adccd04243e09405391a3cbbee1637ea375e27cf2ff"

npm run start
